### PR TITLE
ADI tools

### PR DESCRIPTION
**Pull request by lanzariel**
The following functions for sparse matrices were added:

-  "print_as_full": same as for band matrices; 
-  "plus_sp_mat": adds two sparse matrices setting nzmax as low as possible;
-  "kron": Kronecker product.

The following function for full matrices was added:

-  "kron_mat": Kronecker product.

In particular, "kron" and "plus_sp_mat", had to be implemented using the low level structure of sparse matrices since writing elements with "sp_mat_set" (implementing those algorithms in a naive way) would result in a slower execution.

I had some doubts about "print_as_full" for complex sparse matrices when I saw that the usual printing command is "pnl_sp_mat_complex_prcomplex" rather then "pnl_sp_mat_complex_print" which I would have expected.

I did not update the documentation.

### CODE REVIEW

**Comment by jlelong** [comment]
Thanks for your contribution.

A few things should be added before merging your PR
1. Unit tests are needed for the functions `plus_sp_mat`, `sp_kron` and `kron`. These tests should be added in the `examples` directory.
2. In the functions `plus_sp_mat`, `sp_kron` and `kron`, you need to check that the sizes of the two matrices match.
3. I will add the documentation myself.

**Comment by jlelong** [comment]
I can help you if you grant me access to your `ADItools` branch from the PR page.

**Comment by lanzariel** [comment]
I have updated the `ADItools` branch with the size test for the function `plus_sp_mat`. If I'm not wrong a size check is not necessary for the Kronecker product.
I have granted you the access to my repository.
Thank you very much for your reply

**Comment by jlelong** [comment]
You are right: no size test is required for the Kroenecker product.
Once the unit tests are fine, I will make the merge.

**Comment by lanzariel** [comment]
The unit tests are fine and they passed the checks!

**Pull request merged**
